version: '3.9'

services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
  
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    restart: 'always'
    volumes:
      - ~/db:/var/lib/postgresql/data
    cap_add:
      - SYS_NICE # Deve omitir alertas menores